project_id = "mvjcnonkiwhgffmvfvxg"

[functions.igamewin-callback]
verify_jwt = false

[functions.igamewin-getbalance]
verify_jwt = false

[functions.igamewin-balance-adj]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.process-automations]
verify_jwt = false

[functions.reload-sports]
verify_jwt = false